### ISSUE TITLE
additive fixed effects

### ISSUE THREAD

**Issue by yangyang2000** [amrei-stammann/bife#1]
Noticed the package does not handle additive fixed effects (say fixed effect for an individual and also a fixed effect for location). Is this a limitation of the software or a limitation of the pseudo-demeaning method?

**Comment by amrei-stammann** [comment]
bife cannot concentrate out more than one FE dimension, but  additional FEs can be added as dummies (using factor(location)). Only useful if the number of levels in location is not too large.

More suitable however, is my other R-package alpaca, which concentrates out an arbitrary number of FEs.
