### ISSUE TITLE
Perfect Classification

### ISSUE THREAD

**Issue by lancegui** [amrei-stammann/bife#10]
Could you explain a little more why we can do this? 

"This can be done because these observations do not contribute to the identification of the structural parameters (perfect classification)."

Is this the case in other GLM algorithms? 

Thank you very much!

**Comment by amrei-stammann** [comment]
This is not a technical issue. 
Your question is better suited to be asked here:
https://stats.stackexchange.com/

Short answer:
1. write down the first order partial derivative wrt to the incidental parameter alpha_i 
2. make a case distinction for the two cases  a) all y_it are 0 for individual i  b) all y_it are 1 for individual i
3. you will see that the foc will be 0 for a) when alpha_i tends to minus infinity and for b) when alpha_i tends to plus infinity

For some other GLM (like poisson) you can apply a similar logic.

**Comment by lancegui** [comment]
Thank you very much!
