### ISSUE TITLE
AIC and log-likelihood 

### ISSUE THREAD

**Issue by petrhrobar** [amrei-stammann/bife#2]
Hi
I know that previous version of bife package (fixed effect logic) was calculating AIC and Log-likelihood result and showing then in the summary.

New version does not calculate these values,
Is it possible to add those values back so they would be calculated and printed in summary output?

**Comment by amrei-stammann** [comment]
Hi,

the newest version of `bife` (0.7) has a generic function `logLik()` that returns the sum of the log-likelihood. Based on this value, the AIC can be calculated with the standard formula.

Example:
```
library(bife)
dataset <- psid

mod <- bife(LFP ~ I(AGE^2) + log(INCH) + KID1 + KID2 + KID3 + factor(TIME) | ID, dataset)

# sum of the log-likelihood
LL <- logLik(mod)

# number of parameters
q <- length(coef(mod)) + length(unique(dataset$ID))

# AIC
aic <- - 2.0 * LL + 2.0 * q
aic
```

**Comment by petrhrobar** [comment]
Thank you very mutch
I was NOT aware of this approach
