### ISSUE TITLE
Confussion matrix for BIFE

### ISSUE THREAD

**Issue by petrhrobar** [amrei-stammann/bife#3]
I would like to ask how to calculate confussion matrix for Fixed effect logit model (bife package) with basic logit model (glm) there is no problem, but with Fixed effect logit there is.

For some reason number of predictions is different for logit and fixed effect logit.

```
library(bife)
library(tidyverse)
library(caret)

dataset <- psid

logit <- glm(LFP ~ AGE + I(AGE^2) + log(INCH) + KID1 + KID2 + KID3, data = dataset, family = "binomial")
mod <- bife(LFP ~AGE +  I(AGE^2) + log(INCH) + KID1 + KID2 + KID3| ID, dataset)

summary(mod)
summary(logit)

predict(logit)
predict(mod)

Y <- factor(dataset$LFP)
PRE <- factor(round(predict(logit, type = "response")))
PRE_FIX <- factor(round(predict(mod, type = "response")))

confusionMatrix(Y, PRE)

# Not working
confusionMatrix(Y, PRE_FIX)
```

**Comment by amrei-stammann** [comment]
```
# Working
Ybife <- factor(mod$data$LFP)
confusionMatrix(Ybife, PRE_FIX)
```

Note that `bife` drops perfectly classified observations; i.e. the diagonal elements in your confusion matrix are different than those obtained with  `glm()` .

Don't forget to include dummies in the `glm` formula when comparing the results to `bife`:

```
logit <- glm(LFP ~ AGE + I(AGE^2) + log(INCH) + KID1 + KID2 + KID3 + factor(ID), data = dataset, family = "binomial")
```
