### ISSUE TITLE
Two way FE?

### ISSUE THREAD

**Issue by ramattheis** [amrei-stammann/bife#5]
Hi, great package! 

Is there any way this can be made to accommodate two-way (or arbitrary) fixed effects?

Thanks, and my apologies if this is already possible.

**Comment by amrei-stammann** [comment]
Hi,

please check out my other package alpaca:
https://github.com/amrei-stammann/alpaca

It can estimate glm's with k-way fixed effects and for two-/three-way  fixed effects binary choice models it provides bias corrections.

Best,
Amrei

**Comment by ramattheis** [comment]
Hi, 

Thanks so much! The computation time improvement over glm is huge in my application.  

Thanks again!
